## **Komórki związane z pobraniem danych oraz wyborem danych dla wskazanych klas do dalszej analizy**

In [57]:
import numpy as np
import pandas as pd

#funkcja odpakowująca batch i zwracająca słownik
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [58]:
#odpakowanie danych treningowych (batchów 1-5)
batch1 = unpickle('data_batch_1');
batch2 = unpickle('data_batch_2');
batch3 = unpickle('data_batch_3');
batch4 = unpickle('data_batch_4');
batch5 = unpickle('data_batch_5');

#odpakowanie danych testowych
test_batch = unpickle('test_batch');

#odpakowanie pliku batches.meta
batches = unpickle('batches.meta');

In [59]:
#wyświetlenie nazw labeli określających klasy 
#- szukamy airplane, cat i truck
batches

{b'label_names': [b'airplane',
  b'automobile',
  b'bird',
  b'cat',
  b'deer',
  b'dog',
  b'frog',
  b'horse',
  b'ship',
  b'truck'],
 b'num_cases_per_batch': 10000,
 b'num_vis': 3072}

In [60]:
#funkcja wyciągająca dane i labele ze słowników
def take_data_and_labels(dict):
  X = dict[b'data']
  Y = dict[b'labels']
  return X, Y

In [61]:
def all_classes(batch):
  X, Y = take_data_and_labels(batch)
  #zamiana na obiekty typu dataframe
  df = pd.DataFrame(X)
  df2 = pd.DataFrame(Y)
  #zmiana nazwy kolumny oznaczającej rodzaj klasy
  df2 = df2.rename(columns={0: 'label'})
  #połączenie X i Y w jeden dataframe
  dataset = pd.merge(df, df2, left_index=True, right_index=True, how='outer')
  #wyciągnięcie klas 0, 3 i 9
  dataset0 = dataset.loc[dataset['label'] == 0]
  dataset3 = dataset.loc[dataset['label'] == 3]
  dataset9 = dataset.loc[dataset['label'] == 9]
  #połączenie wszystkich klas w jeden obiekt typu dataframe
  dataset = dataset0.append(dataset3)
  dataset = dataset.append(dataset9)
  return dataset

In [62]:
#połączenie wszystkich batchy w jeden dataframe danych treningowych
batch1_df = all_classes(batch1)
batch2_df = all_classes(batch2)
batch3_df = all_classes(batch3)
batch4_df = all_classes(batch4)
batch5_df = all_classes(batch5)

train = batch1_df.append(batch2_df)
train = train.append(batch3_df)
train = train.append(batch4_df)
train = train.append(batch5_df)
train

0    1    2    3    4    5  ...  3067  3068  3069  3070  3071  label
29    202  202  204  206  208  209  ...   227   237   243   243   243      0
30    126  122  126  127  130  130  ...   113   111   109   107   102      0
35    251  247  247  248  249  248  ...    30    36    35    33    26      0
49    255  255  255  182  181  255  ...   255   255   255   255   255      0
77     44   47   51   54   53   53  ...    48    44    51    52    43      0
...   ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...    ...
9931  183  178  180  182  185  187  ...    77    76    75    75    77      9
9945  255  255  255  253  253  252  ...   255   255   255   255   255      9
9963  147  150  138  122  158  152  ...    93    89    89    88    90      9
9971  229  238  240  253  180   83  ...   125   123   124   126   127      9
9997   35   40   42   39   43   45  ...    93    87    77    66    50      9

[15000 rows x 3073 columns]

In [63]:
#dane testowe
test = all_classes(test_batch)
test

0    1    2    3    4    5  ...  3067  3068  3069  3070  3071  label
3     155  167  176  190  177  166  ...    72    53    50    52    50      0
10     90   90   91   91   93   94  ...   150   149   148   146   146      0
21    247  243  243  244  246  246  ...   239   239   239   237   242      0
27    211  220  223  222  223  223  ...    95    61    32    24    19      0
44     47   46   45   45   46   47  ...    76    73    66    64    65      0
...   ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...    ...
9898   98   97   97   98   98   98  ...   228   227   225   225   224      9
9927  244  241  242  243  244  244  ...   187   188   190   189   187      9
9938  226  228  229  232  232  233  ...    84   103   118   110   124      9
9958   56   31   38   73  122  188  ...   174   182   162    66    51      9
9971  255  249  244  238  228  224  ...    37    52    81    84    85      9

[3000 rows x 3073 columns]

In [64]:
#przetasowanie danych testowych i treningowych
train = train.sample(frac=1)
test = test.sample(frac=1)

In [65]:
#rozdzielenie danych testowych i treningowych na X i y
X_train = train.iloc[:, train.columns != 'label']
y_train = train[['label']]

X_test = test.iloc[:, test.columns != 'label']
y_test = test[['label']]

# **Komórki związane z przetwarzaniem wstępnym**



In [66]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 30)
pca = pca.fit(X_train)
X_train = pca.transform(X_train)

# **Komórki związane z klasyfikacją danych**

In [68]:
from sklearn.svm import SVC

model = SVC(kernel='rbf')
clf = model.fit(X_train, y_train.values.ravel())
X_test_new = pca.transform(X_test)
y_pred = clf.predict(X_test_new)

# **Komórki związane z walidacją modelu (dla danych testowych) wraz z wyznaczeniem i wydrukiem macierzy pomyłek oraz wartości F1**

In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

print("Dokładność: ", accuracy_score(y_test, y_pred))
print("Macierz pomyłek: ")
print(confusion_matrix(y_test, y_pred))
print("F1: ", f1_score(y_test, y_pred, average='weighted'))

Dokładność:  0.8036666666666666
Macierz pomyłek: 
[[799 102  99]
 [ 76 824 100]
 [ 93 119 788]]
F1:  0.803671783799726


# **Komórka przygotowana do testowania z dodatkowym zbiorem testowym**

In [70]:
X_test = pca.transform(X_test)
y_pred = clf.predict(X_test)

print("Dokładność: ", accuracy_score(y_test, y_pred))
print("Macierz pomyłek: ")
print(confusion_matrix(y_test, y_pred))
print("F1: ", f1_score(y_test, y_pred, average='weighted'))

Dokładność:  0.8036666666666666
Macierz pomyłek: 
[[799 102  99]
 [ 76 824 100]
 [ 93 119 788]]
F1:  0.803671783799726
